### ISSUE TITLE
table2text

### ISSUE THREAD

**Issue by adam-dziedzic** [lxuechen/private-transformers#35]
Hi All, thanks for the code. It is not possible to run the prefix option for the table2text. The model for prefix is provided but it is never used. Even when trying to still run the model, another problem occurs, namely the missing code:

https://github.com/lxuechen/private-transformers/blob/18ccc4eab7355e4ac96051a82434796f6aa4624b/examples/table2text/models.py#L112

https://github.com/lxuechen/private-transformers/blob/18ccc4eab7355e4ac96051a82434796f6aa4624b/examples/table2text/models.py#L113

https://github.com/lxuechen/private-transformers/blob/18ccc4eab7355e4ac96051a82434796f6aa4624b/examples/table2text/models.py#L114

Would you provide this part of the code to be able to run prefix for the table2text example?

**Comment by lxuechen** [comment]
I didn't include the prefix-tuning code as part of the release, since it didn't work as well as other methods (if you read my paper, you'll see that). If you want to reimplement it, the prefix-tuning codebase by the original authors or [pefts](https://github.com/huggingface/peft) would be good resources to look into.

**Comment by adam-dziedzic** [comment]
I did read your paper and the method was on par with others for the non-private case. The issue is that it is not possible to reproduce any of the results.
